services:
  app:
    image: financehub:latest
    container_name: financehub-app
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      APP_PORT: ${APP_PORT}
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  postgres:
    container_name: financehub-postgres
    image: postgres:15.8
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: financehub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
