micronaut:
  application:
    name: financehub
  server:
    port: ${APP_PORT:8080}
    context-path: /financehub
    netty:
      access-logger:
        enabled: true
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - "http://localhost:3000"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
  http:
    services:
      alpha-vantage:
        enabled: true
        url: "https://www.alphavantage.co"
        read-timeout: 10s
        exception-on-error-status: true
        apikey: ${ALPHA_VANTAGE_API_KEY:fake}

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
      baselineOnMigrate: true
      baselineVersion: 0

datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/financehub}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
