micronaut:
  application:
    name: financehub
  server:
    port: 8080

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true

datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/financehub
    username: root
    password: root
