micronaut:
  application:
    name: financehub
  server:
    port: 8080
    context-path: /financehub
  http:
    services:
      alpha-vantage:
        url: "https://www.alphavantage.co"
        read-timeout: 10s
        exception-on-error-status: true
        apikey: ${ALPHA_VANTAGE_API_KEY:fake}

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
      baselineOnMigrate: true
      baselineVersion: 0

datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/financehub
    username: root
    password: root

